### ISSUE TITLE
Wrong handling of "plusTime" function

### ISSUE THREAD

**Issue by oleksandrsarapulovgl** [ehn-dcc-development/eu-dcc-business-rules#118]
_dccDateOfBirth_ function returns _JsonDateTime_. And _plusTime_ funtion works only with _TextNode_, but not with _JsonDateTime_

To reproduce - adding _data.txt_ and _logic.txt_ files in attachment.
[logic.txt](https://github.com/ehn-dcc-development/dgc-business-rules/files/8630973/logic.txt)
[data.txt](https://github.com/ehn-dcc-development/dgc-business-rules/files/8630974/data.txt)

Possible fix is below (function _evaluatePlusTime_):

```
internal fun evaluatePlusTime(dateOperand: JsonNode, amount: JsonNode, unit: JsonNode, data: JsonNode): JsonDateTime {

    ...

    if (dateTimeStr !is TextNode) {
        throw RuntimeException("date argument (#1) of \"plusTime\" must be a string")
    }
    return JsonDateTime.fromString(dateTimeStr.asText()).plusTime(amount.intValue(), timeUnit)
}
```

should be changed to

```
internal fun evaluatePlusTime(dateOperand: JsonNode, amount: JsonNode, unit: JsonNode, data: JsonNode): JsonDateTime {

    ...

    if (dateTimeStr !is TextNode && dateTimeStr !is JsonDateTime) {
        throw RuntimeException("date argument (#1) of \"plusTime\" must be a string")
    }
    return JsonDateTime.fromString(dateTimeStr.asText()).plusTime(amount.intValue(), timeUnit)
}
```

**Comment by oleksandrsarapulovgl** [comment]
Hi @dslmeinte could you please check this issue?

**Comment by dslmeinte** [comment]
Hi @oleksandrsarapulovgl ,
Do you mean that you should be able to do something like `plusTime(dccDateOfBirth(<string operand>), <amount>, <time unit>)`?

**Comment by dslmeinte** [comment]
This is intentional/as designed. Can you put the `plusTime` operation “on the other side”? See e.g. the way how we recommend to use `dccDateOfBirth` for exempting non-boostered minors from the maximum validity of 270 days.

(The reason CertLogic is designed this way is that a simple, small language such as this quickly becomes complicated -especially from a type-correctness standpoint- if you give operations a degree of polymorphism. More complicated language means more complicated specification, test suite, tests, etc.)

**Comment by dslmeinte** [comment]
Hi @oleksandrsarapulovgl , Was my previous comment any help/did that the resolve the issue?

**Comment by dslmeinte** [comment]
Glad to hear! Thanks for following up, and closing :)
